# Generated by Django 5.0.6 on 2024-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('semail', models.EmailField(max_length=200)),
                ('snumber', models.IntegerField(max_length=20)),
                ('sage', models.IntegerField(max_length=20)),
                ('senrollment_date', models.DateField(max_length=50)),
                ('scourse', models.CharField(max_length=50)),
            ],
        ),
    ]
