# Generated by Django 5.0.6 on 2024-08-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='sage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='snumber',
            field=models.IntegerField(),
        ),
    ]
